### ISSUE TITLE
Parser

### ISSUE THREAD

**Issue by jvoermans** [jerabaul29/LoggerWavesInIce#2]
@jerabaul29 Hi Jean, I tried the parser using Python 2.7. Only issue is that running the script with the example data provides nearly empty output files. Only data in the output files are the headers, followed by a single number (a zero). Does "verbose" need any changing?
[OUTPUT_FILES.ZIP](https://github.com/jerabaul29/LoggerWavesInIce/files/3747740/OUTPUT_FILES.ZIP)

**Comment by jerabaul29** [comment]
@jvoermans strange. Can you show the full terminal output?

Verbose should not change anything, should be only more or less output in terminal. I had some updates back and forth on this code, will test again on my machine.

**Comment by jvoermans** [comment]
@jerabaul29 I reinstalled Anaconda (Spyder) on my personal computer to get Python 2.7 on it.

I actually tried first on the data provided in the folder. The terminal doesn't give much output, so feels like it is not doing any loop or something:

runfile('C:/Users/Joey/.spyder/Test_Parser/test_process_folder.py', wdir='C:/Users/Joey/.spyder/Test_Parser')
Reloaded modules: parser_logger
Processing file: F00294
Processing file: F00379

That's all in the terminal...

**Comment by jerabaul29** [comment]
Mmmh, you are on Windows I see... Don't know if that may be your problem. Can you use VMWare or other technique to run from Ubuntu or other Linux distro? Otherwise, can you put the verbose value to 10 and see what comes out?

**Comment by jvoermans** [comment]
verbose=10 gives more terminal output, but not in the files

**Comment by jerabaul29** [comment]
Can you show it here?

**Comment by jvoermans** [comment]
Processing file: F00294
Total data length: 138
Current index: 0
Current next two chars: $G
Hit start of a GPS data string
Message: GPRMC,000012.800,V,,,,,0.00,0.00,060180,,,N*49
Current index: 48
Current next two chars: M,
Hit start of a milliseconds timestamp
Message: 4169
Current index: 55
Newline char
Current index: 56
Current next two chars: B,
Hit start of a binary data frame
Print binary data
Length of binary data as ASCII: 154
14 3e 00 3a 00 71 43 b4 bd 82 c8 a4 bd fb 51 d3 3e 3a 6b 99 bf d8 8a 18 c0 f8 26 16 c1 9c 2f 45 b9 e0 bc 9f b6 1f ba 70 bb 3b a5 9b 41 0f 2d cc 42 6b ed 07 43 50 82 e2 c0 c6 ab 63 41 16 86 36 bf 0b 08 27 bf 49 7a 83 3e 65 b5 30 3f 
Validity checksum False
Processing file: F00379
Total data length: 366
Current index: 0
Current next two chars: S,
Hit start of a file
Message: Booting from beginning!
Current index: 26
Newline char
Current index: 27
Current next two chars: R,
Hit start of a raw reading battery message
Message: 0
Current index: 31
Current next two chars: C,
Hit start of a converted level battery message
Message: 0.00
Current index: 38
Current next two chars: M,
Hit start of a milliseconds timestamp
Message: 6865
Current index: 45
Newline char
Current index: 46
Current next two chars: B,
Hit start of a binary data frame
Print binary data
Length of binary data as ASCII: 248
14 3e 00 3a 00 fa 14 3e 00 3a 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 0a 
Validity checksum False
Current index: 175
Current next two chars: M,
Hit start of a milliseconds timestamp
Message: 7885
Current index: 182
Newline char
Current index: 183
Current next two chars: .0
Broken message, read until next line break
Message: 0,0.00,050180,,,N*44
Current index: 206
Current next two chars: M,
Hit start of a milliseconds timestamp
Message: 7898
Current index: 213
Newline char
Current index: 214
Current next two chars: $G
Hit start of a GPS data string
Message: GPVTG,0.00,T,,M,0.00,N,0.00,K,N*32
Current index: 250
Current next two chars: M,
Hit start of a milliseconds timestamp
Message: 7937
Current index: 257
Newline char
Current index: 258
Current next two chars: B,
Hit start of a binary data frame
Print binary data
Length of binary data as ASCII: 206
14 3e 00 3a 00 7d 7f 57 3e 11 89 2d 3d 78 cb f5 3e 6c 85 1c c0 7b ce ab 3f c0 41 15 c1 22 94 41 3b b3 7a 2c b9 68 15 f2 3b b3 7d f3 40 88 96 cc 42 1b 89 31 c3 fd fc 68 c1 70 1d 03 c1 22 8c 77 bf 4c 60 dd 3b 44 6f 82 3e 56 77 2a bd d6 8b 7d bf 9e dd 06 be 96 ba 80 3e fc 44 0d be 23 3f 75 3f 70 aa 69 3e 02 91 
Validity checksum False

**Comment by jvoermans** [comment]
Can it be the different path handling between Linux and Windows? From reading on google, it seems to be the main difference right?

**Comment by jvoermans** [comment]
I had a Linux user try the parser and it worked, so indeed, Windows seems the problem. Let me see if I can get a Linux subsystem on my computer...

**Comment by jvoermans** [comment]
@jerabaul29 Ok it works now! I installed the Windows Subsystem for Linux and went from there.

**Comment by jerabaul29** [comment]
Excellent. Conclusion is, I love Linux and hate Windows. Will update the readme later today.
