### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by trygvekl** [jerabaul29/LoggerWavesInIce#5]
Hi @jerabaul29,

I would like to take a look at the IMU data we sampled in Svalbard, but I am not quite sure how to. I have cloned this repository and as I understand it, I first need to parse the data. I tried to run the test_process_folder.py under /LoggerWavesInIce/Logger_GPS_SD_VN_Binary_output_Parser, but I got the following error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfa in position 53: invalid start byte. Has this got something to do with the fact that I run Python v 3? I already corrected the print syntax in parser_logger.py to Python 3. 

Maybe you can give me a clue on how to proceed here? 

Trygve

**Comment by jerabaul29** [comment]
Ok. This code should work - I and other people used it several times - , but I am afraid that the different encoding used by python3 breaks things. You can either fix the encoding stuff yourself in the code (for this, see how I fixed it when doing the bow measurements analysis), or (maybe simpler) use python 2 by just using the ```python``` command instead of the ```python3``` command (note: you will need to ```sudo pip``` install all necessary packages, even if they had been ```sudo pip3``` installed for python3 before).

**Comment by trygvekl** [comment]
Ok, I'm trying to convert the encoding to python3. I have been able to parse the data, but it is a bit unclear how I should organize the directory tree. I have used only one instrument a couple of hours per day over five days. This gives me typically 15 F0XXXX files per day, in total 67 files. When they are parsed, each file generates 11 new files (F0XXXX_B, etc.). How would you suggest I organize the files with split_data_between_folders.py so that I can best proceed with the further analysis? In process_IMU_data_structure.py, the following tree is suggested (which I find a bit confusing)
![Screenshot from 2020-03-19 12-02-13](https://user-images.githubusercontent.com/48024937/77060993-d32d4300-69d9-11ea-912b-42ec3f6fac88.png)

**Comment by jerabaul29** [comment]
Excellent, great to hear parsing worked!

So basically then you have a single IMU folder, and in this folder you have all your FXXXX files. The files with extensions are the parsed data that you can use for your analysis. Once the parsing has been done, you can have a try at the processing scripts here:

https://github.com/jerabaul29/LoggerWavesInIce/tree/master/processing_scripts

Note that:

- these scripts were developed for looking at much larger amounts of data from more instruments than you have, so you can probably ignore quite a lot of them

- as a consequence, you should only take the scripts as some inspiration / suggestions of how to do your processing.

Note also that the different files are quickly explained in the readme here:

https://github.com/jerabaul29/LoggerWavesInIce/tree/master/Logger_GPS_SD_VN_Binary_output_Parser

If anything is unclear, looking at the code is the documentation in the present case:

https://github.com/jerabaul29/LoggerWavesInIce/blob/0d08f0d129482b25e651786e4eda92d95e46b9a8/Logger_GPS_SD_VN_Binary_output_Parser/parser_logger.py#L229-L401

**Comment by trygvekl** [comment]
Thanks for the help and for the comments. I'm not sure if the parsing worked properly, because the only files with extensions containing any data are FXXXXX_B (196 B) and FXXXXX_P (approx 3.7 MB), all the other extensions for each file seems to be empty. Is this how it is suppose to be? 

From the readme you refer to, I understand it as one need to run the scripts in processing_scrips in a certain order. After the parsing is done one need to run prepare_data_damping.py. This complains a bit about the file extensions being empty and then stops with the following error:
![Screenshot from 2020-03-20 10-22-09](https://user-images.githubusercontent.com/48024937/77150806-fa951600-6a94-11ea-8859-ecc4d9fdc1a7.png)

**Comment by jerabaul29** [comment]
Ok, we can discuss this at the meeting in a few minutes :)

**Comment by trygvekl** [comment]
Python 2 works, thank you for the advice!

**Comment by jerabaul29** [comment]
Perfect, great to hear! :)

**Comment by jerabaul29** [comment]
Working now so closing, feel free to open new issues if you have other problems / questions.
